import React from 'react'
import { Calendar, MapPin, FileText, Share2, Download } from 'lucide-react'
import Card from './ui/Card'
import Button from './ui/Button'

export default function DocumentationPanel({ encounterLogs, stateData }) {
  const generateSummary = (log) => {
    return `ENCOUNTER SUMMARY
Date: ${new Date(log.timestamp).toLocaleString()}
State: ${stateData?.name || log.state}
Location: ${log.location || 'Not captured'}
Notes: ${log.notes || 'No notes recorded'}

YOUR RIGHTS IN ${stateData?.name?.toUpperCase() || log.state?.toUpperCase()}:
${stateData?.rightsSummary || 'Rights information not available'}

This summary was generated by Roadside Rights app.`
  }

  const handleShare = (log) => {
    const summary = generateSummary(log)
    if (navigator.share) {
      navigator.share({
        title: 'Roadside Encounter Summary',
        text: summary
      })
    } else {
      navigator.clipboard.writeText(summary)
      alert('Summary copied to clipboard!')
    }
  }

  const handleDownload = (log) => {
    const summary = generateSummary(log)
    const blob = new Blob([summary], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `encounter-${new Date(log.timestamp).toISOString().split('T')[0]}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="space-y-4 animate-slide-up">
      <div className="bg-surface/10 backdrop-blur-sm rounded-lg p-4 mb-6">
        <h2 className="text-xl font-semibold text-white mb-2">Encounter Logs</h2>
        <p className="text-white/70 text-sm">
          {encounterLogs.length === 0 
            ? 'No encounters logged yet. Use "Get Help Now" during an encounter to start logging.'
            : `${encounterLogs.length} encounter${encounterLogs.length === 1 ? '' : 's'} logged.`
          }
        </p>
      </div>

      {encounterLogs.length === 0 ? (
        <Card className="bg-surface/10 backdrop-blur-sm border border-white/20">
          <div className="p-8 text-center">
            <FileText className="h-12 w-12 text-white/40 mx-auto mb-4" />
            <h3 className="text-lg font-semibold text-white mb-2">No Encounters Yet</h3>
            <p className="text-white/70">
              When you use the "Get Help Now" feature, your encounters will be logged here for future reference.
            </p>
          </div>
        </Card>
      ) : (
        encounterLogs.map((log) => (
          <Card key={log.id} className="bg-surface/10 backdrop-blur-sm border border-white/20">
            <div className="p-4">
              <div className="flex items-start justify-between mb-4">
                <div>
                  <h3 className="font-semibold text-white mb-1">
                    Encounter #{log.id}
                  </h3>
                  <div className="flex items-center gap-4 text-sm text-white/70">
                    <div className="flex items-center gap-1">
                      <Calendar className="h-4 w-4" />
                      {new Date(log.timestamp).toLocaleString()}
                    </div>
                    {log.location && (
                      <div className="flex items-center gap-1">
                        <MapPin className="h-4 w-4" />
                        Location captured
                      </div>
                    )}
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button
                    onClick={() => handleShare(log)}
                    variant="secondary"
                    className="text-xs px-3 py-1"
                  >
                    <Share2 className="h-3 w-3 mr-1" />
                    Share
                  </Button>
                  <Button
                    onClick={() => handleDownload(log)}
                    variant="secondary"
                    className="text-xs px-3 py-1"
                  >
                    <Download className="h-3 w-3 mr-1" />
                    Download
                  </Button>
                </div>
              </div>

              <div className="space-y-3">
                <div>
                  <h4 className="text-sm font-medium text-white/90 mb-1">State</h4>
                  <p className="text-sm text-white/70">{stateData?.name || log.state}</p>
                </div>

                {log.notes && (
                  <div>
                    <h4 className="text-sm font-medium text-white/90 mb-1">Notes</h4>
                    <p className="text-sm text-white/70 whitespace-pre-line">{log.notes}</p>
                  </div>
                )}

                {log.audioRecordingUrl && (
                  <div>
                    <h4 className="text-sm font-medium text-white/90 mb-1">Recording</h4>
                    <p className="text-sm text-accent">Audio recording available (demo)</p>
                  </div>
                )}
              </div>
            </div>
          </Card>
        ))
      )}
    </div>
  )
}